WebApplication1/Controllers/BarangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class BarangsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BarangsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Barangs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Barang.ToListAsync());
        }

        // GET: Barangs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var barang = await _context.Barang
                .FirstOrDefaultAsync(m => m.Id == id);
            if (barang == null)
            {
                return NotFound();
            }

            return View(barang);
        }

        // GET: Barangs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Barangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NamaBarang,In,Out")] Barang barang)
        {
            if (ModelState.IsValid)
            {
                _context.Add(barang);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(barang);
        }

        // GET: Barangs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var barang = await _context.Barang.FindAsync(id);
            if (barang == null)
            {
                return NotFound();
            }
            return View(barang);
        }

        // POST: Barangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NamaBarang,In,Out")] Barang barang)
        {
            if (id != barang.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(barang);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BarangExists(barang.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(barang);
        }

        // GET: Barangs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var barang = await _context.Barang
                .FirstOrDefaultAsync(m => m.Id == id);
            if (barang == null)
            {
                return NotFound();
            }

            return View(barang);
        }

        // POST: Barangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var barang = await _context.Barang.FindAsync(id);
            if (barang != null)
            {
                _context.Barang.Remove(barang);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BarangExists(int id)
        {
            return _context.Barang.Any(e => e.Id == id);
        }
    }
}

WebApplication1/Controllers/DepartemenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class DepartemenController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DepartemenController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Departemen
        public async Task<IActionResult> Index()
        {
            return View(await _context.Departemens.ToListAsync());
        }

        // GET: Departemen/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var departemen = await _context.Departemens
                .FirstOrDefaultAsync(m => m.Id == id);
            if (departemen == null)
            {
                return NotFound();
            }

            return View(departemen);
        }

        // GET: Departemen/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Departemen/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ConsumableName,Brand,Packaging,Unit,MinimumStock,ExpiredDate,ReceivedQuantity,Price,IncomingDate,ConsumptionCost")] Departemen departemen)
        {
            if (ModelState.IsValid)
            {
                _context.Add(departemen);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(departemen);
        }

        // GET: Departemen/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var departemen = await _context.Departemens.FindAsync(id);
            if (departemen == null)
            {
                return NotFound();
            }
            return View(departemen);
        }

        // POST: Departemen/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ConsumableName,Brand,Packaging,Unit,MinimumStock,ExpiredDate,ReceivedQuantity,Price,IncomingDate,ConsumptionCost")] Departemen departemen)
        {
            if (id != departemen.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(departemen);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartemenExists(departemen.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(departemen);
        }

        // GET: Departemen/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var departemen = await _context.Departemens
                .FirstOrDefaultAsync(m => m.Id == id);
            if (departemen == null)
            {
                return NotFound();
            }

            return View(departemen);
        }

        // POST: Departemen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var departemen = await _context.Departemens.FindAsync(id);
            if (departemen != null)
            {
                _context.Departemens.Remove(departemen);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepartemenExists(int id)
        {
            return _context.Departemens.Any(e => e.Id == id);
        }
    }
}

WebApplication1/Controllers/StockBarangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class StockBarangsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StockBarangsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: StockBarangs
        public async Task<IActionResult> Index()
        {
            return View(await _context.StockBarang.ToListAsync());
        }

        // GET: StockBarangs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stockBarang = await _context.StockBarang
                .FirstOrDefaultAsync(m => m.Id == id);
            if (stockBarang == null)
            {
                return NotFound();
            }

            return View(stockBarang);
        }

        // GET: StockBarangs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: StockBarangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NamaBarang,In,Out,Balance")] StockBarang stockBarang)
        {
            if (ModelState.IsValid)
            {
                _context.Add(stockBarang);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(stockBarang);
        }

        // GET: StockBarangs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stockBarang = await _context.StockBarang.FindAsync(id);
            if (stockBarang == null)
            {
                return NotFound();
            }
            return View(stockBarang);
        }

        // POST: StockBarangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NamaBarang,In,Out,Balance")] StockBarang stockBarang)
        {
            if (id != stockBarang.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(stockBarang);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StockBarangExists(stockBarang.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(stockBarang);
        }

        // GET: StockBarangs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stockBarang = await _context.StockBarang
                .FirstOrDefaultAsync(m => m.Id == id);
            if (stockBarang == null)
            {
                return NotFound();
            }

            return View(stockBarang);
        }

        // POST: StockBarangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var stockBarang = await _context.StockBarang.FindAsync(id);
            if (stockBarang != null)
            {
                _context.StockBarang.Remove(stockBarang);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StockBarangExists(int id)
        {
            return _context.StockBarang.Any(e => e.Id == id);
        }
    }
}

WebApplication1/Views/Shared/_Header.cshtml
<header class="header">
    <div class="toggle-btns">
        <a id="toggle-sidebar" href="#">
            <i class="icon-menu1"></i>
        </a>
        <a id="pin-sidebar" href="#">
            <i class="icon-menu1"></i>
        </a>
    </div>
    <div class="header-items">
        <!-- Custom search end -->
        <!-- Header actions start -->
        <ul class="header-actions">
            <li class="dropdown">
            <li class="dropdown">
                <a style="padding-top:1rem;padding-bottom:1rem;" id="userSettings" class="user-settings" data-bs-toggle="dropdown" aria-haspopup="true">
                    <span class=""> Hello, @User.Identity?.Name</span>
                </a>
            </li>
        </ul>
        <!-- Header actions end -->
    </div>
</header>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Chemical</title>
	<!-- Bootstrap css -->
	<link rel="stylesheet" href="~/css/bootstrap.min.css">
	<!-- Icomoon Font Icons css -->
	<link rel="stylesheet" href="~/fonts/style.css">
	<!-- Main css -->
	<link rel="stylesheet" href="~/css/main.css">
</head>
<body>
	<!-- Page wrapper start -->
	<div class="page-wrapper">

		<!-- Sidebar wrapper start -->
		<partial name="_Sidebar" />
		<!-- Sidebar wrapper end -->

		<!-- Page content start  -->
		<div class="page-content">
			<partial name="_Header" />
			
			<!-- Page header start -->
			<div class="page-header">
			</div>
			<!-- Page header end -->
			<!-- Main container start -->
			<div class="main-container">
				<main role="main">
					@RenderBody()
				</main>
			</div>
			<!-- Main container end -->

		</div>
		<!-- Page content end -->

	</div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

	<!-- Required jQuery first, then Bootstrap Bundle JS -->
	<script src="~/js/jquery.min.js"></script>
	<script src="~/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/moment.js"></script>	


	<!-- *************
		************ Vendor Js Files *************
	************* -->
	<!-- Slimscroll JS -->
	<script src="~/vendor/slimscroll/slimscroll.min.js"></script>
	<script src="~/vendor/slimscroll/custom-scrollbar.js"></script>

	<!-- Daterange -->
	<script src="~/vendor/daterange/daterange.js"></script>
	<script src="~/vendor/daterange/custom-daterange.js"></script>

	<!-- Apex Charts -->
	<script src="~/vendor/apex/apexcharts.min.js"></script>
	<script src="~/vendor/apex/admin/visitors.js"></script>
	<script src="~/vendor/apex/admin/deals.js"></script>
	<script src="~/vendor/apex/admin/income.js"></script>
	<script src="~/vendor/apex/admin/customers.js"></script>

	<!-- Main JS -->
	<script src="~/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication1/Views/Shared/_Sidebar.cshtml
<nav id="sidebar" class="sidebar-wrapper">

	<!-- Sidebar brand start  -->
	<div class="w-100 d-flex">
		<a class="navbar-brand mx-auto flex-fill text-center" asp-controller="home" asp-action="index" style="margin-top:20px;">
			<img src="~/img/LOGO.png" width="auto" height="24" alt="Website Logo" class="d-block mx-auto">
		</a>
	</div>
	<hr style="margin-top:1rem;margin-bottom:0;"> <!-- Sidebar brand end  -->
	<!-- Sidebar content start -->
	<div class="sidebar-content">

		<!-- sidebar menu start -->
		<div class="sidebar-menu">
			<ul>
				<li class="header-menu">USER</li>
				<li>
					<a asp-controller="Departemen" asp-action="Index">
						<i class="icon-message-circle"></i>
						<span class="menu-text">Dashboard</span>
					</a>
				</li>
				<li>
					<a href="chat.html">
						<i class="icon-message-circle"></i>
						<span class="menu-text">Request Bahan Chemical</span>
					</a>
				</li>
				<li class="sidebar-dropdown">
					<a href="#">
						<i class="icon-devices_other"></i>
						<span class="menu-text">Bahan Chemical</span>
					</a>
					<div class="sidebar-submenu">
						<ul>
							<li>
								<a asp-controller="Home" asp-action="Index">Ortho Phosphoric Acid 85%</a>
							</li>
							<li>
								<a asp-controller="Departemen" asp-action="Index">Ethanolamine </a>
							</li>
							<li>
								<a asp-controller="StockBarangs" asp-action="Index">Dimethyl Sulfoxide (DMSO)2</a>
							</li><li>
								<a asp-controller="Barangs" asp-action="Index">Hydrochloric Acid (HCl) 37%</a>
							</li><li>
								<a href="sales-dashboard.html">Hydrogen Peroxide (H2O2) 30%</a>
							</li><li>
								<a href="sales-dashboard.html">Nitric Acid (HNO3) 69-70%</a>
							</li><li>
								<a href="sales-dashboard.html">Nitric Acid (HNO3) 100%</a>
							</li><li>
								<a href="sales-dashboard.html">Potassium Hydroxide (KOH)</a>
							</li><li>
								<a href="sales-dashboard.html">REN HY (Hardener)</a>
							</li><li>
								<a href="sales-dashboard.html">Sulfuric Acid 95~97%</a>
							</li><li>
								<a href="sales-dashboard.html">Ammonia Solution (NH4OH) 25%</a>
							</li><li>
								<a href="sales-dashboard.html">Acetone</a>
							</li><li>
								<a href="sales-dashboard.html">Araldyte</a>
							</li>
						</ul>
					</div>
				</li>
				
				<li class="header-menu">ADMIN</li>
				<li class="sidebar-dropdown">
					<a href="#">
						<i class="icon-devices_other"></i>
						<span class="menu-text">Dashboards</span>
					</a>
					<div class="sidebar-submenu">
						<ul>
							<li>
								<a href="index.html">Admin Dashboard</a>
							</li>
							<li>
								<a href="sales-dashboard.html">Sales Dashboard</a>
							</li>
							<li>
						</ul>
					</div>
				</li>
				<li>
					<a href="chat.html">
						<i class="icon-message-circle"></i>
						<span class="menu-text">Request</span>
					</a>
				</li>
			</ul>
		</div>
		<!-- sidebar menu end -->

	</div>
	<!-- Sidebar content end -->

</nav>